#!/usr/bin/env bash
#Displays numbers from 1 to 100.

for (( n=1; n<=100; n++ ))
do
    if ( ((i % 15 == 0)) ) then echo "FizzBuzz";
       elif ( ((i % 5 == 0)) ) then echo "Buzz";
       elif ( ((i % 3 == 0)) ) then echo "Fizz";
       else
       echo "$i";
       fi
       (( i++ ))
done
