#!/usr/bin/env bash
# Displays "Holberton School" 10x times, after the 9th ite displays Hi
x=1
while [ $x -le 10 ]
do
    echo "Holberton School"
    if [ $x -eq 9 ]
    then 
        echo "Hi"
    fi
    ((x++))
done
